coala-header.svg: Fix coala.io text rendering
coala-analyzer/coala-design pull request #54
Opened 2018-10-20 12:48 UTC by sangamcse

The previous version of coala-header.svg has text rendering
problem seen with both `a` of `coala`. This fixes those with
better SVG format created using Inkscape.

Closes https://github.com/coala/artwork/issues/53

2018-10-20 14:59 UTC, ayan-b approved these changes
LGTM.

2018-10-21 15:35 UTC, jayvdb requested changes
The diff is unreadable.

The actual content changes cant be seen.

Split this into two commits, one which changes the style, and the other which changes the content.

2018-10-21 16:23 UTC, sangamcse commented
@jayvdb TBH, these changes in SVG XML format is done by Inkscape which I tried to reduce. My only concern was the logo text rendering which was a bit odd in the previous version but this change looks little satisfying to my eyes. 😄

2018-10-21 17:20 UTC, jayvdb requested changes

2018-10-21 17:20 UTC, jayvdb commented on artwork/logo/coala-header.svg
> +<svg version="1.1"
moving version isnt part of "fix coala.io text..."

2018-10-21 17:20 UTC, jayvdb commented on artwork/logo/coala-header.svg
> +   id="svg3781"
the old `id` value was better

2018-10-21 17:20 UTC, jayvdb commented on artwork/logo/coala-header.svg
> +   viewBox="0 0 193.2 41.1"
these changes should be done in the other commit.

I doubt this is part of fixing coala.io, but it is a sensible change as part of fixing the file structure (the other commit).
```diff
-viewBox="0 0 193.2 41.099998"
+viewBox="0 0 193.2 41.1
```

2018-10-21 17:20 UTC, jayvdb commented
the commit message of https://github.com/coala/artwork/pull/54/commits/ead8a4c83d6 is a bit odd.

"betterSVG."

ALso `version="1.1"` is moved twice in these two patches - returning to the same spot in the second patch.

Can we use https://developer.mozilla.org/en-US/docs/Web/SVG/Element/image to put 'coala.io' text in a separate SVG  file which is re-usable , and also to re-use the real coala logo svg instead of creating a copy?

It would be better to try using https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text for the 'coala.io'

2018-10-21 20:28 UTC, sangamcse commented
@jayvdb, I agree. Tried creating one at https://github.com/sangamcse/artwork/blob/coala-text/artwork/logo/coala_io_text.svg. Is it ok?
> Can we use https://developer.mozilla.org/en-US/docs/Web/SVG/Element/image to put 'coala.io' text in a separate SVG file which is re-usable, and also to re-use the real coala logo SVG instead of creating a copy?

2018-10-24 03:48 UTC, jayvdb commented
The o in `.io` isnt rendering for me in Falkon.

@ayan-b can you check?

2018-10-24 07:45 UTC, sangamcse commented
> Can we use https://developer.mozilla.org/en-US/docs/Web/SVG/Element/image to put 'coala.io' text in a separate SVG file which is re-usable , and also to re-use the real coala logo svg instead of creating a copy?

Created an issue for separate `coala.io` text. https://github.com/coala/artwork/issues/56

2018-10-28 03:49 UTC, jayvdb approved these changes

2018-10-28 03:49 UTC, jayvdb commented
ack https://github.com/coala/artwork/pull/54/commits/e6575798b824c2318d4382c9a73730876ef45c63

2018-10-28 03:50 UTC, jayvdb commented
@gitmate-bot ff

2018-10-28 03:50 UTC, jayvdb commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being fastforwarded automatically. Please **DO NOT** push while fastforward is in progress or your changes would be lost permanently :warning:

2018-10-28 03:50 UTC, merged

2018-10-28 03:50 UTC, jayvdb commented
Automated fastforward with [GitMate.io](https://gitmate.io) was successful! :tada: