Added new 404 artwork for GCI
coala-analyzer/coala-design pull request #66
Opened 2018-11-02 21:01 UTC by yambati03

2018-11-03 05:07 UTC, li-boxuan commented on artwork/popup_display/coala404.svg
> +<svg id="f8ddba2a-7a5d-4c08-9401-016d01f79fe7" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 1920 1080"><defs><style>.\36 c8fafb0-39d8
Can you break it down to more lines?
Also missing newline at EOF :)

2018-11-03 06:54 UTC, srivama reviewed
Nice idea there, Yashas 👍 The logo, description and 404 aren't centre aligned w.r.to the svg dimensions though. Please make the amendments :)

2018-11-03 07:08 UTC, ayan-b commented
Really nice! Next time onwards keep your master branch clean and do your work in a different branch! :smiley:

2018-11-05 09:07 UTC, KVGarg requested changes
@yambati03 Commit message isn't in the correct format, have a look at [commit guidelines](http://coala.io/commit) to improve your commit message. 
Please also [rebase](https://coala.io/rebase) ;-)

2018-11-05 12:33 UTC, sangamcse commented
ack 628592fc67bcbffc7597331025cc6390e54b5848

2018-11-05 12:33 UTC, sangamcse commented
@gitmate-bot ff

2018-11-05 12:33 UTC, jayvdb commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being fastforwarded automatically. Please **DO NOT** push while fastforward is in progress or your changes would be lost permanently :warning:

2018-11-05 12:36 UTC, jayvdb commented
Automated fastforward failed! Please fastforward your pull request manually via the command line.

Reason:
```
Command: git push upstream HEAD:master

Exit Code: 1

Cause:

remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: At least 1 approving review is required by reviewers with write access.        
To <hidden_oauth_token>
 ! [remote rejected] HEAD -> master (protected branch hook declined)
error: failed to push some refs to '<hidden_oauth_token>'


```

2018-11-05 12:37 UTC, sangamcse approved these changes

2018-11-05 12:37 UTC, sangamcse commented
@gitmate-bot ff

2018-11-05 12:37 UTC, jayvdb commented
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being fastforwarded automatically. Please **DO NOT** push while fastforward is in progress or your changes would be lost permanently :warning:

2018-11-05 12:39 UTC, merged

2018-11-05 12:39 UTC, jayvdb commented
Automated fastforward with [GitMate.io](https://gitmate.io) was successful! :tada: